# Generated by Django 5.2.6 on 2025-10-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_moviedetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
