# Generated by Django 5.2.6 on 2025-10-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_moviedetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='description',
            field=models.TextField(),
        ),
    ]
