# Generated by Django 5.2.6 on 2025-10-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('designation', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('image', models.ImageField(upload_to='employees')),
            ],
        ),
    ]
